#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep  6 15:45:12 2020

@author: xuebinwang
"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import accuracy_score
import pandas as pd


df = pd.read_csv("/Users/xuebinwang/Desktop/IE 517/hw/hw2/Treasury Squeeze test - DS1.csv" )

X = df.iloc[:,2:11]

y = df.iloc[:, 11]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

sc = StandardScaler()
sc.fit(X_train)
sc.fit(X_test)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

dt = DecisionTreeClassifier(criterion='gini', 
                              max_depth=4, 
                              random_state=1)

dt.fit(X_train_std, y_train)

y_pred = dt.predict(X_test_std)


print(accuracy_score(y_test, y_pred))





