#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep  6 16:19:55 2020

@author: xuebinwang
"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("/Users/xuebinwang/Desktop/IE 517/hw/hw2/Treasury Squeeze test - DS1.csv" )
X = df.iloc[:,2:11]

y = df.iloc[:, 11]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=5,p=2,metric='minkowski')
k_range = range(1,26)
scores = []
for k in k_range:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_std, y_train)
    y_pred = knn.predict(X_test_std)
    scores.append(accuracy_score(y_test,y_pred))
print(scores)

plt.plot(k_range, scores, color="b", linestyle="-", marker="^", linewidth=1)
plt.xlabel("number of neighbors")
plt.ylabel("accuracy")
plt.show()
